### ISSUE TITLE
Feature Request: Import data from Quirk

### ISSUE THREAD

**Issue by tswast** [erosson/freecbt#107]
Thanks for keeping this project going! I really appreciate Quirk and am glad to see you keeping it maintained.

As someone who has recently switched to FreeCBT, I'd love to be able to import my history from Quirk to see how far I've come.

**Comment by erosson** [comment]
I wish this were possible, but Quirk would need a way to export data. Even if Quirk's author found time to implement exporting, it'd still be no good for Quirk on Android, which is no longer on the play store.

Import/export for FreeCBT itself is probably worth adding, so I'll leave this open, though it still won't/can't help with Quirk data.

**Comment by erosson** [comment]
Exporting/importing FreeCBT data should (finally) be live in a couple of days! https://github.com/erosson/freecbt/commit/68799984aab10550a811dfc05b0c6ad338f72333

Sadly, there's still no way to export old Quirk data.
