### ISSUE TITLE
ios release

### ISSUE THREAD

**Issue by erosson** [erosson/freecbt#3]
[quirk ios still exists](https://apps.apple.com/us/app/quirk-cbt/id1447026451), so this is not urgent - but there's no guarantee it will continue to exist

I don't really know anything about ios dev

it's [$100/year](https://developer.apple.com/programs/how-it-works/), which I'm (grudgingly) willing to pay. I think their dev tools only work on macs, but I don't own one and would rather not get another computer, especially one I'd rarely need - can I do everything through expo, or rent a cloud mac somehow? I expect app updates (vs. ota updates through expo) will be rare enough that occasionally borrowing a friend's mac for a few hours isn't out of the question.

**Comment by blitzmohit** [comment]
I am willing to help with the ios port, both in terms of getting a developer license to launch the app & trying to maintain it though my knowledge of ios is limited. I do have some prior experience with React Native. Let me know what you think.

**Comment by erosson** [comment]
Thank you Mohit!

I am working on this next - now that Android is sorted out, it's probably best to get Apple's review process started.

Spent the evening setting up/paying for an apple dev account, and got freecbt's first `.ipa` build. expo *can* build without a mac, it just needs auth for a developer account. 

I have an ipad but no other apple devices. Turns out the ipad was required - needed an apple device to enable 2fa on my account for some reason, and 2fa is required before paying for a developer account

---

Open questions/tasks - Mohit, if you (or anyone else reading) know the answer to any of these, feel free to chime in - no pressure, I'll start researching tomorrow if not:

* How do I put this `.ipa` on the app store? I can't seem to upload it from the web, https://appstoreconnect.apple.com/
  * [Looks like I need to have a mac/xcode for this step](https://forums.expo.io/t/build-expo-ios-without-mac-and-ios-phone/27426/2)
  * [MacInCloud](https://checkout.macincloud.com/) isn't cheap, but we shouldn't need to use it very often.
* How do I test this `.ipa` on my ipad, before sending it off for app store review? Is this another thing I can't do from windows/linux?
  * I *can* test by downloading the expo client to my ipad. maybe that's enough and I don't need to test the ipa build?
  * the ipad expo app seems to be stuck on freecbt's splash screen - why?, fix it
* Finish preparing the storefront - get screenshots together; upload them; keywords

**Comment by erosson** [comment]
version 1 release steps:

* increment either version or build-number in app.json
* `expo build:ios`, wait for build: https://expo.io/
* remote desktop to macincloud: https://portal.macincloud.com/#/servers/payg (this starts billing)
  * https://expo.io/ > login > download fresh-built ipa
  * transporter > login > select fresh-built ipa > upload
  * apple menu > logout (this stops billing)
* https://appstoreconnect.apple.com/ > activity > wait for new build to finish processing (it'll send an email, ~20 min later)

it looks like fastlane automates a bunch of this, so if we need to do lots of non-ota updates for some reason it might be worth learning

---

only after these steps can I test the ipa on my ipad. (good thing I did, first build used phone resolution/claimed no ipad support.)

no need for review with private testing/users I explicitly invite. public testing is possible, but requires review at least for version 1, so probably easiest to skip that.

**Comment by erosson** [comment]
> Your app is being prepared for App Review.

:beers:

**Comment by erosson** [comment]
> [Congratulations! We're pleased to let you know that your app, FreeCBT, has been approved for the App Store.](https://apps.apple.com/us/app/freecbt/id1516063390)

:tada: :tada: :tada: 

quicker than I expected!
