### ISSUE TITLE
Fdroid or provide apk 

### ISSUE THREAD

**Issue by krillin666** [erosson/freecbt#391]
Thank you for maintaining the app alive. 
However, following the spirit of open source could you not provide the apk file or publish it to Fdroid for those of use who do not want to use Google ?

Thank you once again !

**Comment by filippodebortoli** [comment]
Hi,

it would be possible to submit a request to include freeCBT in the F-Droid repository (more info [here](https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md)). One requirement is to inform the original app author. @erosson would you be in favor of having the app added to F-Droid? If so, I could take care of issuing the submission myself.

Thank you for keeping this fork of Quirk alive!

**Comment by erosson** [comment]
I'm not at all opposed to an f-droid release or an apk build! I've never interacted with f-droid, so @filippodebortoli , if you'd like to submit FreeCBT there, I'm all for it.

Here's the most recent apk build - built just now with `expo build:android -t apk` - completely untested, so let me know if it's broken:
https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/android/%40erosson/freecbt-6fa47c4104454afab8c74921a99b123e-signed.apk

...but an APK really ought to be built and released as part of [the existing CI process](https://github.com/erosson/freecbt/blob/master/.github/workflows/deploy.yml), and without relying on expo's build servers: https://docs.expo.dev/classic/turtle-cli/

**Comment by erosson** [comment]
an apk is now automatically built + released for each new git tag! https://github.com/erosson/freecbt/releases

**Comment by saltedcoffii** [comment]
It still would be nice to have an F-Droid app for automatic updating capability, is someone working on this?
