### ISSUE TITLE
web version, via react-native for web

### ISSUE THREAD

**Issue by erosson** [erosson/freecbt#7]
a web version would increase the app's reach, reduce dependence on app stores, and ease my development/testing process

I'm not sure how much extra work this would take - it *sounds* like [react-native-web](https://github.com/necolas/react-native-web) isn't hard to add, but there's always a catch. do abandon this if it ends up not worth the trouble; very low priority

this issue is distinct from #2 - this is a web version of the app which does not yet exist, #2 is https://quirk.fyi

**Comment by erosson** [comment]
fiddled with this a little today - there are some third-party packages (`react-native-pose`, `react-native-snap-carousel`) that aren't designed for `react-native-web`.

I could probably patch out animations from `pose` for just the web version - but `carousel` is a bit more fundamental to the cbt form input.

Not worth the effort right now.

**Comment by mdeguzis** [comment]
I use this app a lot and would like to maybe mess around with this so that when I want to write a bit more text while on my laptop, I can type on my laptop vs my phone. Do you have a set of suggested dev docs or anything? I don't mind taking a look.

**Comment by erosson** [comment]
> I use this app a lot and would like to maybe mess around with this so that when I want to write a bit more text while on my laptop, I can type on my laptop vs my phone. Do you have a set of suggested dev docs or anything? I don't mind taking a look.

This is actually already done, very recently! It's not yet advertised - likely still buggy, needs more testing and other release-prep stuff - but feel free to try it out early since you're interested:

https://freecbt.erosson.org/webapp/

**Comment by mdeguzis** [comment]
Thank you so much!!!!

**Comment by mdeguzis** [comment]
on my screen, the right side doesn't auto size, so I had to zoom out to see it: 

<img width="1867" height="750" alt="Image" src="https://github.com/user-attachments/assets/95921567-9b87-48e0-b53b-5f8a15c135b4" />

Seems there are some scaling issues: 

<img width="1616" height="1051" alt="Image" src="https://github.com/user-attachments/assets/44fc91f8-f0e1-40cf-836a-4f514c505450" />

<img width="1616" height="1051" alt="Image" src="https://github.com/user-attachments/assets/c2cd9f5e-8eee-496e-a1aa-c1d9c736871f" />

Could we please reopen this so we can keep this testing feedback in-scope?

Help page is sized correctly: 

<img width="1616" height="1051" alt="Image" src="https://github.com/user-attachments/assets/dc2bce51-988e-4eea-b58c-93904b1ad19f" />

Settings area sized correctly:

<img width="1616" height="1051" alt="Image" src="https://github.com/user-attachments/assets/8d787713-8cac-4a8b-ab2d-310eae9046af" />
